# Generated by Django 3.2.2 on 2021-06-26 12:59

from django.db import migrations, models
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('passtoken', models.CharField(default=users.models.passToken, max_length=40, unique=True)),
            ],
        ),
    ]
